#!/usr/bin/env bash
#command to be displayed if less than 3 parameters passed

if [ $# -lt 4 ]
then
	  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	    exit 1
	    fi

#Bash script that transfers a file from our client to a server
cp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"


if [ $? -eq 0 ]
then
	  echo "FILE TRANSFER WAS SUCCESSFULL"
  else
	    echo "FILE TRANSFER FAILED"
fi
