#!/usr/bin/env bash
#Install nginx web server


sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# this to test nginx
sudo nginx -t

# this is to reload the service
sudo service nginx reload
