#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

# this to test nginx
sudo nginx -t

# this is to reload the service
sudo service nginx reload
