#!/usr/bin/env bash
# th Script used to Display "Best School" 10 times.
string_a='Best School'
# shellcheck Disable=SC2034 
# Unused Variable Left To Hold Count Values
for (( c=1; c<=10; c++ ))
do
    echo "Best School"
done
