#!/usr/bin/env bash
# th Script used to Display "Best School" 10 times.
string_a='Best School'
# shellcheck Disable=SC2034 
# Unused Variable Left To Hold Count Values
for i in {1..10}; do echo "$string_a"; done
